apiVersion: v1
kind: Service
metadata:
  name: {{ include "wotlwedu-minimal.fullname" . }}
  labels:
    {{- include "wotlwedu-minimal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wotlwedu-minimal.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
