{{- $service := deepCopy .Values.service -}}
{{- $environment := default "" .Values.environment -}}
{{- if and $environment (hasKey .Values.environments $environment) -}}
  {{- $envConfig := index .Values.environments $environment -}}
  {{- if hasKey $envConfig "service" -}}
    {{- $service = mergeOverwrite $service $envConfig.service -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wotlwedu-minimal.fullname" . }}
  labels:
    {{- include "wotlwedu-minimal.labels" . | nindent 4 }}
spec:
  type: {{ $service.type }}
  selector:
    {{- include "wotlwedu-minimal.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ $service.httpsPort }}
      targetPort: https
      protocol: TCP
